/***************************************************************
 * Copyright (C) 2012
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ***************************************************************/

/* FILE NAME   : TSG.H
 * PURPOSE     : Tough Space Graphics library.
 *               Main declaration module.
 * PROGRAMMER  : CGSG'2004-2005-2006-2012.
 *               Vitaly A. Galinsky.
 * LAST UPDATE : 29.11.2012 (from 13.08.2006, from 14.04.2006)
 * NOTE        : Templates namespace 'tsg'.
 *               Based on
 *                 Tatyana Marchukova (vector & matrices) &
 *                 Valeriya Nikolaenko (camera) code.
 *                 (last updates 25.03.2005 & 20.05.2005) 
 *               Based on TSGRAPH project from 'C' library.
 *                 (last updates 2004/2003/1999, original 1998)
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum
 */

#ifndef _TSG_H_
#define _TSG_H_

#include "tsgdef.h"

#include "tsgvect.h"
#include "tsgcolor.h"
#include "tsgmatrx.h"
#include "tsgtrans.h"
#include "tsgstock.h"
#include "tsgcam.h"
#include "tsgray.h"
#include "tsgquat.h"
//#include "tsgplane.h"

#endif /* _TSG_H_ */

/* END OF 'TSG.H' FILE */
